
trainer:
  accelerator: 'cpu'
  log_every_n_steps: 10
#  accumulate_grad_batches: 5
#  gradient_clip_val: 0.5

  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: 'epoch'

    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
          monitor: "val_loss"
          mode: "min"
          save_top_k: 1
          filename: "{epoch}_{val_loss:.2f}"
          enable_version_counter: true
          dirpath: ./checkpoints

    - class_path: utils.CustomWriter
      init_args:
        output_dir: ./predictions

#    - class_path: lightning.pytorch.callbacks.StochasticWeightAveraging
#      init_args:
#        swa_lrs: 1e-2

optimizer:
  lr: 0.01

lr_scheduler:
  gamma: 0.99

data:
  choice_path: ../../../../../trip-choices.csv
  trip_path: ../../table-trips.csv
  person_path: ../../table-persons.csv

  choices: [walk, pt, car, bike, ride]

  features:
    - age
    - income
    - car_valid
    - pt_valid

  mode_features:
    - km
    - hours
    - daily_cost
    - distance_cost

#  variations: 32
#  batch_size: 8192

model:
  layers: [64, 32, 16]
#   layers: [8, 8]
